FROM alpine:3
RUN apk add php81 php81-pdo_mysql php81-xml php81-mbstring php81-gd php81-zip php81-curl php81-zip nodejs npm
RUN ln -s /usr/bin/php81 /usr/bin/php
WORKDIR /app
CMD ["npm", "run", "start"]
